name: ResidentialTreatment
favicon: null
layout_spectrum: 0.3763381252065301
typography_spectrum: 0.6439779005013406
title: 'InnerChange: Trusted Therapeutic Programs'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.30796835967339575
  lightness: 0.6813734674360603
  saturation: 0.6861810246482491
  rhythmicContrast: 0.6198011562228203
purpose: []
